export type ChainEnv =
  | 'local'
  | 'arbitrumTestnet'
  | 'arbitrum'
  | 'blastTestnet'
  | 'blast'
  | 'mantleTestnet'
  | 'mantle'
  | 'seiTestnet'
  | 'sei'
  | 'baseTestnet'
  | 'base'
  | 'sonicTestnet'
  | 'sonic'
  | 'beraTestnet';
