/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface IAirdropInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "claim"
      | "claimToLBA"
      | "getClaimed"
      | "getClaimedLBA"
      | "getClaimingDeadlines"
      | "vest"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "claim",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "claimToLBA",
    values: [BigNumberish, BigNumberish, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimed",
    values: [BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimedLBA",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClaimingDeadlines",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "vest",
    values: [BigNumberish, BigNumberish, BigNumberish, BytesLike[]]
  ): string;

  decodeFunctionResult(functionFragment: "claim", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "claimToLBA", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getClaimed", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getClaimedLBA",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClaimingDeadlines",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "vest", data: BytesLike): Result;
}

export interface IAirdrop extends BaseContract {
  connect(runner?: ContractRunner | null): IAirdrop;
  waitForDeployment(): Promise<this>;

  interface: IAirdropInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  claim: TypedContractMethod<
    [
      epoch: BigNumberish,
      amount: BigNumberish,
      totalAmount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  claimToLBA: TypedContractMethod<
    [amount: BigNumberish, totalAmount: BigNumberish, proof: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getClaimed: TypedContractMethod<
    [epoch: BigNumberish, account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getClaimedLBA: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getClaimingDeadlines: TypedContractMethod<[], [bigint[]], "nonpayable">;

  vest: TypedContractMethod<
    [
      epoch: BigNumberish,
      amount: BigNumberish,
      totalAmount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "claim"
  ): TypedContractMethod<
    [
      epoch: BigNumberish,
      amount: BigNumberish,
      totalAmount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimToLBA"
  ): TypedContractMethod<
    [amount: BigNumberish, totalAmount: BigNumberish, proof: BytesLike[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaimed"
  ): TypedContractMethod<
    [epoch: BigNumberish, account: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClaimedLBA"
  ): TypedContractMethod<[account: AddressLike], [bigint], "nonpayable">;
  getFunction(
    nameOrSignature: "getClaimingDeadlines"
  ): TypedContractMethod<[], [bigint[]], "nonpayable">;
  getFunction(
    nameOrSignature: "vest"
  ): TypedContractMethod<
    [
      epoch: BigNumberish,
      amount: BigNumberish,
      totalAmount: BigNumberish,
      proof: BytesLike[]
    ],
    [void],
    "nonpayable"
  >;

  filters: {};
}
