/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IEndpoint {
  export type BurnLpStruct = {
    sender: BytesLike;
    productId: BigNumberish;
    amount: BigNumberish;
    nonce: BigNumberish;
  };

  export type BurnLpStructOutput = [
    sender: string,
    productId: bigint,
    amount: bigint,
    nonce: bigint
  ] & { sender: string; productId: bigint; amount: bigint; nonce: bigint };

  export type BurnLpAndTransferStruct = {
    sender: BytesLike;
    productId: BigNumberish;
    amount: BigNumberish;
    recipient: BytesLike;
  };

  export type BurnLpAndTransferStructOutput = [
    sender: string,
    productId: bigint,
    amount: bigint,
    recipient: string
  ] & { sender: string; productId: bigint; amount: bigint; recipient: string };

  export type ClaimSequencerFeesStruct = { subaccount: BytesLike };

  export type ClaimSequencerFeesStructOutput = [subaccount: string] & {
    subaccount: string;
  };

  export type DepositCollateralStruct = {
    sender: BytesLike;
    productId: BigNumberish;
    amount: BigNumberish;
  };

  export type DepositCollateralStructOutput = [
    sender: string,
    productId: bigint,
    amount: bigint
  ] & { sender: string; productId: bigint; amount: bigint };

  export type DepositInsuranceStruct = { amount: BigNumberish };

  export type DepositInsuranceStructOutput = [amount: bigint] & {
    amount: bigint;
  };

  export type LiquidateSubaccountStruct = {
    sender: BytesLike;
    liquidatee: BytesLike;
    productId: BigNumberish;
    isEncodedSpread: boolean;
    amount: BigNumberish;
    nonce: BigNumberish;
  };

  export type LiquidateSubaccountStructOutput = [
    sender: string,
    liquidatee: string,
    productId: bigint,
    isEncodedSpread: boolean,
    amount: bigint,
    nonce: bigint
  ] & {
    sender: string;
    liquidatee: string;
    productId: bigint;
    isEncodedSpread: boolean;
    amount: bigint;
    nonce: bigint;
  };

  export type MintLpStruct = {
    sender: BytesLike;
    productId: BigNumberish;
    amountBase: BigNumberish;
    quoteAmountLow: BigNumberish;
    quoteAmountHigh: BigNumberish;
    nonce: BigNumberish;
  };

  export type MintLpStructOutput = [
    sender: string,
    productId: bigint,
    amountBase: bigint,
    quoteAmountLow: bigint,
    quoteAmountHigh: bigint,
    nonce: bigint
  ] & {
    sender: string;
    productId: bigint;
    amountBase: bigint;
    quoteAmountLow: bigint;
    quoteAmountHigh: bigint;
    nonce: bigint;
  };

  export type SettlePnlStruct = {
    subaccounts: BytesLike[];
    productIds: BigNumberish[];
  };

  export type SettlePnlStructOutput = [
    subaccounts: string[],
    productIds: bigint[]
  ] & { subaccounts: string[]; productIds: bigint[] };

  export type TransferQuoteStruct = {
    sender: BytesLike;
    recipient: BytesLike;
    amount: BigNumberish;
    nonce: BigNumberish;
  };

  export type TransferQuoteStructOutput = [
    sender: string,
    recipient: string,
    amount: bigint,
    nonce: bigint
  ] & { sender: string; recipient: string; amount: bigint; nonce: bigint };
}

export interface IClearinghouseInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addEngine"
      | "burnLp"
      | "burnLpAndTransfer"
      | "claimSequencerFees"
      | "depositCollateral"
      | "depositInsurance"
      | "getClearinghouseLiq"
      | "getEndpoint"
      | "getEngineByProduct"
      | "getEngineByType"
      | "getHealth"
      | "getInsurance"
      | "getQuote"
      | "getSpreads"
      | "getVersion"
      | "liquidateSubaccount"
      | "mintLp"
      | "registerProduct"
      | "settlePnl"
      | "transferQuote"
      | "upgradeClearinghouseLiq"
      | "withdrawCollateral"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClearinghouseInitialized"
      | "Liquidation"
      | "ModifyCollateral"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addEngine",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "burnLp",
    values: [IEndpoint.BurnLpStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "burnLpAndTransfer",
    values: [IEndpoint.BurnLpAndTransferStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "claimSequencerFees",
    values: [IEndpoint.ClaimSequencerFeesStruct, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "depositCollateral",
    values: [IEndpoint.DepositCollateralStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "depositInsurance",
    values: [IEndpoint.DepositInsuranceStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "getClearinghouseLiq",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEndpoint",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineByProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineByType",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getHealth",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getInsurance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "getQuote", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "getSpreads",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getVersion",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "liquidateSubaccount",
    values: [IEndpoint.LiquidateSubaccountStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "mintLp",
    values: [IEndpoint.MintLpStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "registerProduct",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlePnl",
    values: [IEndpoint.SettlePnlStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "transferQuote",
    values: [IEndpoint.TransferQuoteStruct]
  ): string;
  encodeFunctionData(
    functionFragment: "upgradeClearinghouseLiq",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawCollateral",
    values: [BytesLike, BigNumberish, BigNumberish, AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addEngine", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "burnLp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "burnLpAndTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "claimSequencerFees",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositCollateral",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositInsurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClearinghouseLiq",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEndpoint",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineByProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineByType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getHealth", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getInsurance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getQuote", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getSpreads", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getVersion", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "liquidateSubaccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintLp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "registerProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "settlePnl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferQuote",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "upgradeClearinghouseLiq",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawCollateral",
    data: BytesLike
  ): Result;
}

export namespace ClearinghouseInitializedEvent {
  export type InputTuple = [endpoint: AddressLike, quote: AddressLike];
  export type OutputTuple = [endpoint: string, quote: string];
  export interface OutputObject {
    endpoint: string;
    quote: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace LiquidationEvent {
  export type InputTuple = [
    liquidatorSubaccount: BytesLike,
    liquidateeSubaccount: BytesLike,
    productId: BigNumberish,
    isEncodedSpread: boolean,
    amount: BigNumberish,
    amountQuote: BigNumberish
  ];
  export type OutputTuple = [
    liquidatorSubaccount: string,
    liquidateeSubaccount: string,
    productId: bigint,
    isEncodedSpread: boolean,
    amount: bigint,
    amountQuote: bigint
  ];
  export interface OutputObject {
    liquidatorSubaccount: string;
    liquidateeSubaccount: string;
    productId: bigint;
    isEncodedSpread: boolean;
    amount: bigint;
    amountQuote: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModifyCollateralEvent {
  export type InputTuple = [
    amount: BigNumberish,
    subaccount: BytesLike,
    productId: BigNumberish
  ];
  export type OutputTuple = [
    amount: bigint,
    subaccount: string,
    productId: bigint
  ];
  export interface OutputObject {
    amount: bigint;
    subaccount: string;
    productId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IClearinghouse extends BaseContract {
  connect(runner?: ContractRunner | null): IClearinghouse;
  waitForDeployment(): Promise<this>;

  interface: IClearinghouseInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addEngine: TypedContractMethod<
    [
      engine: AddressLike,
      offchainExchange: AddressLike,
      engineType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  burnLp: TypedContractMethod<
    [tx: IEndpoint.BurnLpStruct],
    [void],
    "nonpayable"
  >;

  burnLpAndTransfer: TypedContractMethod<
    [txn: IEndpoint.BurnLpAndTransferStruct],
    [void],
    "nonpayable"
  >;

  claimSequencerFees: TypedContractMethod<
    [tx: IEndpoint.ClaimSequencerFeesStruct, fees: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  depositCollateral: TypedContractMethod<
    [tx: IEndpoint.DepositCollateralStruct],
    [void],
    "nonpayable"
  >;

  depositInsurance: TypedContractMethod<
    [tx: IEndpoint.DepositInsuranceStruct],
    [void],
    "nonpayable"
  >;

  getClearinghouseLiq: TypedContractMethod<[], [string], "view">;

  getEndpoint: TypedContractMethod<[], [string], "view">;

  getEngineByProduct: TypedContractMethod<
    [productId: BigNumberish],
    [string],
    "view"
  >;

  getEngineByType: TypedContractMethod<
    [engineType: BigNumberish],
    [string],
    "view"
  >;

  getHealth: TypedContractMethod<
    [subaccount: BytesLike, healthType: BigNumberish],
    [bigint],
    "view"
  >;

  getInsurance: TypedContractMethod<[], [bigint], "view">;

  getQuote: TypedContractMethod<[], [string], "view">;

  getSpreads: TypedContractMethod<[], [bigint], "view">;

  getVersion: TypedContractMethod<[], [bigint], "view">;

  liquidateSubaccount: TypedContractMethod<
    [tx: IEndpoint.LiquidateSubaccountStruct],
    [void],
    "nonpayable"
  >;

  mintLp: TypedContractMethod<
    [tx: IEndpoint.MintLpStruct],
    [void],
    "nonpayable"
  >;

  registerProduct: TypedContractMethod<
    [productId: BigNumberish],
    [void],
    "nonpayable"
  >;

  settlePnl: TypedContractMethod<
    [tx: IEndpoint.SettlePnlStruct],
    [void],
    "nonpayable"
  >;

  transferQuote: TypedContractMethod<
    [tx: IEndpoint.TransferQuoteStruct],
    [void],
    "nonpayable"
  >;

  upgradeClearinghouseLiq: TypedContractMethod<
    [_clearinghouseLiq: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawCollateral: TypedContractMethod<
    [
      sender: BytesLike,
      productId: BigNumberish,
      amount: BigNumberish,
      sendTo: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addEngine"
  ): TypedContractMethod<
    [
      engine: AddressLike,
      offchainExchange: AddressLike,
      engineType: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnLp"
  ): TypedContractMethod<[tx: IEndpoint.BurnLpStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "burnLpAndTransfer"
  ): TypedContractMethod<
    [txn: IEndpoint.BurnLpAndTransferStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "claimSequencerFees"
  ): TypedContractMethod<
    [tx: IEndpoint.ClaimSequencerFeesStruct, fees: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositCollateral"
  ): TypedContractMethod<
    [tx: IEndpoint.DepositCollateralStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "depositInsurance"
  ): TypedContractMethod<
    [tx: IEndpoint.DepositInsuranceStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClearinghouseLiq"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEndpoint"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEngineByProduct"
  ): TypedContractMethod<[productId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getEngineByType"
  ): TypedContractMethod<[engineType: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getHealth"
  ): TypedContractMethod<
    [subaccount: BytesLike, healthType: BigNumberish],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getInsurance"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getQuote"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getSpreads"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getVersion"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "liquidateSubaccount"
  ): TypedContractMethod<
    [tx: IEndpoint.LiquidateSubaccountStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintLp"
  ): TypedContractMethod<[tx: IEndpoint.MintLpStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "registerProduct"
  ): TypedContractMethod<[productId: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "settlePnl"
  ): TypedContractMethod<[tx: IEndpoint.SettlePnlStruct], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferQuote"
  ): TypedContractMethod<
    [tx: IEndpoint.TransferQuoteStruct],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "upgradeClearinghouseLiq"
  ): TypedContractMethod<
    [_clearinghouseLiq: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "withdrawCollateral"
  ): TypedContractMethod<
    [
      sender: BytesLike,
      productId: BigNumberish,
      amount: BigNumberish,
      sendTo: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClearinghouseInitialized"
  ): TypedContractEvent<
    ClearinghouseInitializedEvent.InputTuple,
    ClearinghouseInitializedEvent.OutputTuple,
    ClearinghouseInitializedEvent.OutputObject
  >;
  getEvent(
    key: "Liquidation"
  ): TypedContractEvent<
    LiquidationEvent.InputTuple,
    LiquidationEvent.OutputTuple,
    LiquidationEvent.OutputObject
  >;
  getEvent(
    key: "ModifyCollateral"
  ): TypedContractEvent<
    ModifyCollateralEvent.InputTuple,
    ModifyCollateralEvent.OutputTuple,
    ModifyCollateralEvent.OutputObject
  >;

  filters: {
    "ClearinghouseInitialized(address,address)": TypedContractEvent<
      ClearinghouseInitializedEvent.InputTuple,
      ClearinghouseInitializedEvent.OutputTuple,
      ClearinghouseInitializedEvent.OutputObject
    >;
    ClearinghouseInitialized: TypedContractEvent<
      ClearinghouseInitializedEvent.InputTuple,
      ClearinghouseInitializedEvent.OutputTuple,
      ClearinghouseInitializedEvent.OutputObject
    >;

    "Liquidation(bytes32,bytes32,uint32,bool,int128,int128)": TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;
    Liquidation: TypedContractEvent<
      LiquidationEvent.InputTuple,
      LiquidationEvent.OutputTuple,
      LiquidationEvent.OutputObject
    >;

    "ModifyCollateral(int128,bytes32,uint32)": TypedContractEvent<
      ModifyCollateralEvent.InputTuple,
      ModifyCollateralEvent.OutputTuple,
      ModifyCollateralEvent.OutputObject
    >;
    ModifyCollateral: TypedContractEvent<
      ModifyCollateralEvent.InputTuple,
      ModifyCollateralEvent.OutputTuple,
      ModifyCollateralEvent.OutputObject
    >;
  };
}
