/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "./common";

export interface ILBAInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "depositUsdc"
      | "depositVrtx"
      | "getStage"
      | "lockedLpBalance"
      | "lpBalance"
      | "maxWithdrawableUsdc"
      | "vrtxInitialPriceX18"
      | "withdrawLiquidity"
      | "withdrawUsdc"
      | "withdrawableLpBalance"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "depositUsdc",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "depositVrtx",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "getStage", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "lockedLpBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "lpBalance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "maxWithdrawableUsdc",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "vrtxInitialPriceX18",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawLiquidity",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawUsdc",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawableLpBalance",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "depositUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositVrtx",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getStage", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "lockedLpBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "lpBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "maxWithdrawableUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "vrtxInitialPriceX18",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawLiquidity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawUsdc",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawableLpBalance",
    data: BytesLike
  ): Result;
}

export interface ILBA extends BaseContract {
  connect(runner?: ContractRunner | null): ILBA;
  waitForDeployment(): Promise<this>;

  interface: ILBAInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  depositUsdc: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  depositVrtx: TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getStage: TypedContractMethod<[], [bigint], "view">;

  lockedLpBalance: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  lpBalance: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  maxWithdrawableUsdc: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  vrtxInitialPriceX18: TypedContractMethod<[], [bigint], "view">;

  withdrawLiquidity: TypedContractMethod<
    [lpAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawUsdc: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  withdrawableLpBalance: TypedContractMethod<
    [account: AddressLike],
    [bigint],
    "view"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "depositUsdc"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "depositVrtx"
  ): TypedContractMethod<
    [account: AddressLike, amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getStage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "lockedLpBalance"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "lpBalance"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "maxWithdrawableUsdc"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "vrtxInitialPriceX18"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "withdrawLiquidity"
  ): TypedContractMethod<[lpAmount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawUsdc"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawableLpBalance"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;

  filters: {};
}
