/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IProductEngine {
  export type ProductDeltaStruct = {
    productId: BigNumberish;
    subaccount: BytesLike;
    amountDelta: BigNumberish;
    vQuoteDelta: BigNumberish;
  };

  export type ProductDeltaStructOutput = [
    productId: bigint,
    subaccount: string,
    amountDelta: bigint,
    vQuoteDelta: bigint
  ] & {
    productId: bigint;
    subaccount: string;
    amountDelta: bigint;
    vQuoteDelta: bigint;
  };
}

export declare namespace IPerpEngine {
  export type BalanceStruct = {
    amount: BigNumberish;
    vQuoteBalance: BigNumberish;
    lastCumulativeFundingX18: BigNumberish;
  };

  export type BalanceStructOutput = [
    amount: bigint,
    vQuoteBalance: bigint,
    lastCumulativeFundingX18: bigint
  ] & {
    amount: bigint;
    vQuoteBalance: bigint;
    lastCumulativeFundingX18: bigint;
  };

  export type LpBalanceStruct = {
    amount: BigNumberish;
    lastCumulativeFundingX18: BigNumberish;
  };

  export type LpBalanceStructOutput = [
    amount: bigint,
    lastCumulativeFundingX18: bigint
  ] & { amount: bigint; lastCumulativeFundingX18: bigint };

  export type LpStateStruct = {
    supply: BigNumberish;
    lastCumulativeFundingX18: BigNumberish;
    cumulativeFundingPerLpX18: BigNumberish;
    base: BigNumberish;
    quote: BigNumberish;
  };

  export type LpStateStructOutput = [
    supply: bigint,
    lastCumulativeFundingX18: bigint,
    cumulativeFundingPerLpX18: bigint,
    base: bigint,
    quote: bigint
  ] & {
    supply: bigint;
    lastCumulativeFundingX18: bigint;
    cumulativeFundingPerLpX18: bigint;
    base: bigint;
    quote: bigint;
  };

  export type StateStruct = {
    cumulativeFundingLongX18: BigNumberish;
    cumulativeFundingShortX18: BigNumberish;
    availableSettle: BigNumberish;
    openInterest: BigNumberish;
  };

  export type StateStructOutput = [
    cumulativeFundingLongX18: bigint,
    cumulativeFundingShortX18: bigint,
    availableSettle: bigint,
    openInterest: bigint
  ] & {
    cumulativeFundingLongX18: bigint;
    cumulativeFundingShortX18: bigint;
    availableSettle: bigint;
    openInterest: bigint;
  };
}

export interface IPerpEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyDeltas"
      | "burnLp"
      | "decomposeLps"
      | "getBalance"
      | "getBalances"
      | "getClearinghouse"
      | "getEngineType"
      | "getLpState"
      | "getOrderbook"
      | "getPositionPnl"
      | "getProductIds"
      | "getSettlementState"
      | "getStateAndBalance"
      | "getStatesAndBalances"
      | "hasBalance"
      | "initialize"
      | "manualAssert"
      | "mintLp"
      | "settlePnl"
      | "socializeSubaccount"
      | "swapLp(uint32,int128,int128)"
      | "swapLp(uint32,int128,int128,int128,int128)"
      | "updateProduct"
      | "updateStates"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AddProduct"): EventFragment;

  encodeFunctionData(
    functionFragment: "applyDeltas",
    values: [IProductEngine.ProductDeltaStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burnLp",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decomposeLps",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalance",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getBalances",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClearinghouse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getLpState",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderbook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getPositionPnl",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getSettlementState",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStateAndBalance",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getStatesAndBalances",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasBalance",
    values: [BigNumberish, BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "manualAssert",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "mintLp",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "settlePnl",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "socializeSubaccount",
    values: [BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapLp(uint32,int128,int128)",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapLp(uint32,int128,int128,int128,int128)",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProduct",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "updateStates",
    values: [BigNumberish, BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "applyDeltas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnLp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decomposeLps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getBalance", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClearinghouse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "getLpState", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getOrderbook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getPositionPnl",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getSettlementState",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStateAndBalance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getStatesAndBalances",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "hasBalance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "manualAssert",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "mintLp", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "settlePnl", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "socializeSubaccount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapLp(uint32,int128,int128)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapLp(uint32,int128,int128,int128,int128)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProduct",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateStates",
    data: BytesLike
  ): Result;
}

export namespace AddProductEvent {
  export type InputTuple = [productId: BigNumberish];
  export type OutputTuple = [productId: bigint];
  export interface OutputObject {
    productId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IPerpEngine extends BaseContract {
  connect(runner?: ContractRunner | null): IPerpEngine;
  waitForDeployment(): Promise<this>;

  interface: IPerpEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyDeltas: TypedContractMethod<
    [deltas: IProductEngine.ProductDeltaStruct[]],
    [void],
    "nonpayable"
  >;

  burnLp: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike, amountLp: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  decomposeLps: TypedContractMethod<
    [liquidatee: BytesLike, liquidator: BytesLike, feeCalculator: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getBalance: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [IPerpEngine.BalanceStructOutput],
    "view"
  >;

  getBalances: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [[IPerpEngine.LpBalanceStructOutput, IPerpEngine.BalanceStructOutput]],
    "view"
  >;

  getClearinghouse: TypedContractMethod<[], [string], "view">;

  getEngineType: TypedContractMethod<[], [bigint], "view">;

  getLpState: TypedContractMethod<
    [productId: BigNumberish],
    [IPerpEngine.LpStateStructOutput],
    "view"
  >;

  getOrderbook: TypedContractMethod<
    [productId: BigNumberish],
    [string],
    "view"
  >;

  getPositionPnl: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [bigint],
    "view"
  >;

  getProductIds: TypedContractMethod<[], [bigint[]], "view">;

  getSettlementState: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [
      [
        bigint,
        IPerpEngine.LpStateStructOutput,
        IPerpEngine.LpBalanceStructOutput,
        IPerpEngine.StateStructOutput,
        IPerpEngine.BalanceStructOutput
      ] & {
        availableSettle: bigint;
        lpState: IPerpEngine.LpStateStructOutput;
        lpBalance: IPerpEngine.LpBalanceStructOutput;
        state: IPerpEngine.StateStructOutput;
        balance: IPerpEngine.BalanceStructOutput;
      }
    ],
    "view"
  >;

  getStateAndBalance: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [[IPerpEngine.StateStructOutput, IPerpEngine.BalanceStructOutput]],
    "view"
  >;

  getStatesAndBalances: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [
      [
        IPerpEngine.LpStateStructOutput,
        IPerpEngine.LpBalanceStructOutput,
        IPerpEngine.StateStructOutput,
        IPerpEngine.BalanceStructOutput
      ]
    ],
    "view"
  >;

  hasBalance: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [boolean],
    "view"
  >;

  initialize: TypedContractMethod<
    [
      _clearinghouse: AddressLike,
      _quote: AddressLike,
      _endpoint: AddressLike,
      _admin: AddressLike,
      _fees: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  manualAssert: TypedContractMethod<
    [openInterests: BigNumberish[]],
    [void],
    "view"
  >;

  mintLp: TypedContractMethod<
    [
      productId: BigNumberish,
      subaccount: BytesLike,
      amountBase: BigNumberish,
      quoteAmountLow: BigNumberish,
      quoteAmountHigh: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  settlePnl: TypedContractMethod<
    [subaccount: BytesLike, productIds: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  socializeSubaccount: TypedContractMethod<
    [subaccount: BytesLike, insurance: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  "swapLp(uint32,int128,int128)": TypedContractMethod<
    [
      productId: BigNumberish,
      baseDelta: BigNumberish,
      quoteDelta: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;

  "swapLp(uint32,int128,int128,int128,int128)": TypedContractMethod<
    [
      productId: BigNumberish,
      amount: BigNumberish,
      priceX18: BigNumberish,
      sizeIncrement: BigNumberish,
      lpSpreadX18: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;

  updateProduct: TypedContractMethod<[txn: BytesLike], [void], "nonpayable">;

  updateStates: TypedContractMethod<
    [dt: BigNumberish, avgPriceDiffs: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyDeltas"
  ): TypedContractMethod<
    [deltas: IProductEngine.ProductDeltaStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnLp"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike, amountLp: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decomposeLps"
  ): TypedContractMethod<
    [liquidatee: BytesLike, liquidator: BytesLike, feeCalculator: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getBalance"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [IPerpEngine.BalanceStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getBalances"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [[IPerpEngine.LpBalanceStructOutput, IPerpEngine.BalanceStructOutput]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getClearinghouse"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEngineType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getLpState"
  ): TypedContractMethod<
    [productId: BigNumberish],
    [IPerpEngine.LpStateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "getOrderbook"
  ): TypedContractMethod<[productId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getPositionPnl"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "getProductIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "getSettlementState"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [
      [
        bigint,
        IPerpEngine.LpStateStructOutput,
        IPerpEngine.LpBalanceStructOutput,
        IPerpEngine.StateStructOutput,
        IPerpEngine.BalanceStructOutput
      ] & {
        availableSettle: bigint;
        lpState: IPerpEngine.LpStateStructOutput;
        lpBalance: IPerpEngine.LpBalanceStructOutput;
        state: IPerpEngine.StateStructOutput;
        balance: IPerpEngine.BalanceStructOutput;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStateAndBalance"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [[IPerpEngine.StateStructOutput, IPerpEngine.BalanceStructOutput]],
    "view"
  >;
  getFunction(
    nameOrSignature: "getStatesAndBalances"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [
      [
        IPerpEngine.LpStateStructOutput,
        IPerpEngine.LpBalanceStructOutput,
        IPerpEngine.StateStructOutput,
        IPerpEngine.BalanceStructOutput
      ]
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "hasBalance"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _clearinghouse: AddressLike,
      _quote: AddressLike,
      _endpoint: AddressLike,
      _admin: AddressLike,
      _fees: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "manualAssert"
  ): TypedContractMethod<[openInterests: BigNumberish[]], [void], "view">;
  getFunction(
    nameOrSignature: "mintLp"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      subaccount: BytesLike,
      amountBase: BigNumberish,
      quoteAmountLow: BigNumberish,
      quoteAmountHigh: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "settlePnl"
  ): TypedContractMethod<
    [subaccount: BytesLike, productIds: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "socializeSubaccount"
  ): TypedContractMethod<
    [subaccount: BytesLike, insurance: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapLp(uint32,int128,int128)"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      baseDelta: BigNumberish,
      quoteDelta: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapLp(uint32,int128,int128,int128,int128)"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      amount: BigNumberish,
      priceX18: BigNumberish,
      sizeIncrement: BigNumberish,
      lpSpreadX18: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProduct"
  ): TypedContractMethod<[txn: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "updateStates"
  ): TypedContractMethod<
    [dt: BigNumberish, avgPriceDiffs: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "AddProduct"
  ): TypedContractEvent<
    AddProductEvent.InputTuple,
    AddProductEvent.OutputTuple,
    AddProductEvent.OutputObject
  >;

  filters: {
    "AddProduct(uint32)": TypedContractEvent<
      AddProductEvent.InputTuple,
      AddProductEvent.OutputTuple,
      AddProductEvent.OutputObject
    >;
    AddProduct: TypedContractEvent<
      AddProductEvent.InputTuple,
      AddProductEvent.OutputTuple,
      AddProductEvent.OutputObject
    >;
  };
}
