/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace IProductEngine {
  export type ProductDeltaStruct = {
    productId: BigNumberish;
    subaccount: BytesLike;
    amountDelta: BigNumberish;
    vQuoteDelta: BigNumberish;
  };

  export type ProductDeltaStructOutput = [
    productId: bigint,
    subaccount: string,
    amountDelta: bigint,
    vQuoteDelta: bigint
  ] & {
    productId: bigint;
    subaccount: string;
    amountDelta: bigint;
    vQuoteDelta: bigint;
  };
}

export interface IProductEngineInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "applyDeltas"
      | "burnLp"
      | "decomposeLps"
      | "getClearinghouse"
      | "getEngineType"
      | "getOrderbook"
      | "getProductIds"
      | "initialize"
      | "mintLp"
      | "swapLp(uint32,int128,int128)"
      | "swapLp(uint32,int128,int128,int128,int128)"
      | "updateProduct"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "AddProduct"): EventFragment;

  encodeFunctionData(
    functionFragment: "applyDeltas",
    values: [IProductEngine.ProductDeltaStruct[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burnLp",
    values: [BigNumberish, BytesLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "decomposeLps",
    values: [BytesLike, BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getClearinghouse",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getEngineType",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getOrderbook",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getProductIds",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "initialize",
    values: [AddressLike, AddressLike, AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mintLp",
    values: [BigNumberish, BytesLike, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapLp(uint32,int128,int128)",
    values: [BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "swapLp(uint32,int128,int128,int128,int128)",
    values: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "updateProduct",
    values: [BytesLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "applyDeltas",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burnLp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "decomposeLps",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getClearinghouse",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getEngineType",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getOrderbook",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getProductIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "initialize", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mintLp", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "swapLp(uint32,int128,int128)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "swapLp(uint32,int128,int128,int128,int128)",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateProduct",
    data: BytesLike
  ): Result;
}

export namespace AddProductEvent {
  export type InputTuple = [productId: BigNumberish];
  export type OutputTuple = [productId: bigint];
  export interface OutputObject {
    productId: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IProductEngine extends BaseContract {
  connect(runner?: ContractRunner | null): IProductEngine;
  waitForDeployment(): Promise<this>;

  interface: IProductEngineInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  applyDeltas: TypedContractMethod<
    [deltas: IProductEngine.ProductDeltaStruct[]],
    [void],
    "nonpayable"
  >;

  burnLp: TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike, amountLp: BigNumberish],
    [bigint],
    "nonpayable"
  >;

  decomposeLps: TypedContractMethod<
    [liquidatee: BytesLike, liquidator: BytesLike, feeCalculator: AddressLike],
    [bigint],
    "nonpayable"
  >;

  getClearinghouse: TypedContractMethod<[], [string], "view">;

  getEngineType: TypedContractMethod<[], [bigint], "view">;

  getOrderbook: TypedContractMethod<
    [productId: BigNumberish],
    [string],
    "view"
  >;

  getProductIds: TypedContractMethod<[], [bigint[]], "view">;

  initialize: TypedContractMethod<
    [
      _clearinghouse: AddressLike,
      _quote: AddressLike,
      _endpoint: AddressLike,
      _admin: AddressLike,
      _fees: AddressLike
    ],
    [void],
    "nonpayable"
  >;

  mintLp: TypedContractMethod<
    [
      productId: BigNumberish,
      subaccount: BytesLike,
      amountBase: BigNumberish,
      quoteAmountLow: BigNumberish,
      quoteAmountHigh: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  "swapLp(uint32,int128,int128)": TypedContractMethod<
    [
      productId: BigNumberish,
      baseDelta: BigNumberish,
      quoteDelta: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;

  "swapLp(uint32,int128,int128,int128,int128)": TypedContractMethod<
    [
      productId: BigNumberish,
      amount: BigNumberish,
      priceX18: BigNumberish,
      sizeIncrement: BigNumberish,
      lpSpreadX18: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;

  updateProduct: TypedContractMethod<[txn: BytesLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "applyDeltas"
  ): TypedContractMethod<
    [deltas: IProductEngine.ProductDeltaStruct[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burnLp"
  ): TypedContractMethod<
    [productId: BigNumberish, subaccount: BytesLike, amountLp: BigNumberish],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "decomposeLps"
  ): TypedContractMethod<
    [liquidatee: BytesLike, liquidator: BytesLike, feeCalculator: AddressLike],
    [bigint],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getClearinghouse"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "getEngineType"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "getOrderbook"
  ): TypedContractMethod<[productId: BigNumberish], [string], "view">;
  getFunction(
    nameOrSignature: "getProductIds"
  ): TypedContractMethod<[], [bigint[]], "view">;
  getFunction(
    nameOrSignature: "initialize"
  ): TypedContractMethod<
    [
      _clearinghouse: AddressLike,
      _quote: AddressLike,
      _endpoint: AddressLike,
      _admin: AddressLike,
      _fees: AddressLike
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "mintLp"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      subaccount: BytesLike,
      amountBase: BigNumberish,
      quoteAmountLow: BigNumberish,
      quoteAmountHigh: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapLp(uint32,int128,int128)"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      baseDelta: BigNumberish,
      quoteDelta: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "swapLp(uint32,int128,int128,int128,int128)"
  ): TypedContractMethod<
    [
      productId: BigNumberish,
      amount: BigNumberish,
      priceX18: BigNumberish,
      sizeIncrement: BigNumberish,
      lpSpreadX18: BigNumberish
    ],
    [[bigint, bigint]],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateProduct"
  ): TypedContractMethod<[txn: BytesLike], [void], "nonpayable">;

  getEvent(
    key: "AddProduct"
  ): TypedContractEvent<
    AddProductEvent.InputTuple,
    AddProductEvent.OutputTuple,
    AddProductEvent.OutputObject
  >;

  filters: {
    "AddProduct(uint32)": TypedContractEvent<
      AddProductEvent.InputTuple,
      AddProductEvent.OutputTuple,
      AddProductEvent.OutputObject
    >;
    AddProduct: TypedContractEvent<
      AddProductEvent.InputTuple,
      AddProductEvent.OutputTuple,
      AddProductEvent.OutputObject
    >;
  };
}
