import { ChainEnv } from '@vertex-protocol/contracts';

export const ENGINE_CLIENT_ENDPOINTS: Record<ChainEnv, string> = {
  local: 'http://localhost:80',
  arbitrumTestnet: 'https://gateway.sepolia-test.vertexprotocol.com/v1',
  blastTestnet: 'https://gateway.blast-test.vertexprotocol.com/v1',
  arbitrum: 'https://gateway.prod.vertexprotocol.com/v1',
  blast: 'https://gateway.blast-prod.vertexprotocol.com/v1',
  mantleTestnet: 'https://gateway.mantle-test.vertexprotocol.com/v1',
  mantle: 'https://gateway.mantle-prod.vertexprotocol.com/v1',
  seiTestnet: 'https://gateway.sei-test.vertexprotocol.com/v1',
  sei: 'https://gateway.sei-prod.vertexprotocol.com/v1',
  baseTestnet: 'https://gateway.base-test.vertexprotocol.com/v1',
  base: 'https://gateway.base-prod.vertexprotocol.com/v1',
  sonicTestnet: 'https://gateway.sonic-test.vertexprotocol.com/v1',
  sonic: 'https://gateway.sonic-prod.vertexprotocol.com/v1',
  beraTestnet: 'https://gateway.bera-test.vertexprotocol.com/v1',
  abstractTestnet: 'https://gateway.abstract-test.vertexprotocol.com/v1',
  abstract: 'https://gateway.abstract-prod.vertexprotocol.com/v1',
  bera: 'https://gateway.bera-prod.vertexprotocol.com/v1',
  avaxTestnet: 'https://gateway.avax-test.vertexprotocol.com/v1',
  avax: 'https://gateway.avax-prod.vertexprotocol.com/v1',
};

export const ENGINE_WS_CLIENT_ENDPOINTS: Record<ChainEnv, string> = {
  local: 'ws://localhost:80',
  arbitrumTestnet: 'wss://gateway.sepolia-test.vertexprotocol.com/v1/ws',
  blastTestnet: 'wss://gateway.blast-test.vertexprotocol.com/v1/ws',
  arbitrum: 'wss://gateway.prod.vertexprotocol.com/v1/ws',
  blast: 'wss://gateway.blast-prod.vertexprotocol.com/v1/ws',
  mantleTestnet: 'wss://gateway.mantle-test.vertexprotocol.com/v1/ws',
  mantle: 'wss://gateway.mantle-prod.vertexprotocol.com/v1/ws',
  seiTestnet: 'wss://gateway.sei-test.vertexprotocol.com/v1/ws',
  sei: 'wss://gateway.sei-prod.vertexprotocol.com/v1/ws',
  baseTestnet: 'wss://gateway.base-test.vertexprotocol.com/v1/ws',
  base: 'wss://gateway.base-prod.vertexprotocol.com/v1/ws',
  sonicTestnet: 'wss://gateway.sonic-test.vertexprotocol.com/v1/ws',
  sonic: 'wss://gateway.sonic-prod.vertexprotocol.com/v1/ws',
  beraTestnet: 'wss://gateway.bera-test.vertexprotocol.com/v1/ws',
  abstractTestnet: 'wss://gateway.abstract-test.vertexprotocol.com/v1/ws',
  abstract: 'wss://gateway.abstract-prod.vertexprotocol.com/v1/ws',
  bera: 'wss://gateway.bera-prod.vertexprotocol.com/v1/ws',
  avaxTestnet: 'wss://gateway.avax-test.vertexprotocol.com/v1/ws',
  avax: 'wss://gateway.avax-prod.vertexprotocol.com/v1/ws',
};

export const ENGINE_WS_SUBSCRIPTION_CLIENT_ENDPOINTS: Record<ChainEnv, string> =
  {
    local: 'ws://localhost:80',
    arbitrumTestnet:
      'wss://gateway.sepolia-test.vertexprotocol.com/v1/subscribe',
    blastTestnet: 'wss://gateway.blast-test.vertexprotocol.com/v1/subscribe',
    arbitrum: 'wss://gateway.prod.vertexprotocol.com/v1/subscribe',
    blast: 'wss://gateway.blast-prod.vertexprotocol.com/v1/subscribe',
    mantleTestnet: 'wss://gateway.mantle-test.vertexprotocol.com/v1/subscribe',
    mantle: 'wss://gateway.mantle-prod.vertexprotocol.com/v1/subscribe',
    seiTestnet: 'wss://gateway.sei-test.vertexprotocol.com/v1/subscribe',
    sei: 'wss://gateway.sei-prod.vertexprotocol.com/v1/subscribe',
    baseTestnet: 'wss://gateway.base-test.vertexprotocol.com/v1/subscribe',
    base: 'wss://gateway.base-prod.vertexprotocol.com/v1/subscribe',
    sonicTestnet: 'wss://gateway.sonic-test.vertexprotocol.com/v1/subscribe',
    sonic: 'wss://gateway.sonic-prod.vertexprotocol.com/v1/subscribe',
    beraTestnet: 'wss://gateway.bera-test.vertexprotocol.com/v1/subscribe',
    abstractTestnet:
      'wss://gateway.abstract-test.vertexprotocol.com/v1/subscribe',
    abstract: 'wss://gateway.abstract-prod.vertexprotocol.com/v1/subscribe',
    bera: 'wss://gateway.bera-prod.vertexprotocol.com/v1/subscribe',
    avaxTestnet: 'wss://gateway.avax-test.vertexprotocol.com/v1/subscribe',
    avax: 'wss://gateway.avax-prod.vertexprotocol.com/v1/subscribe',
  };
